spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unlatravel?serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
    #password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
server:
  port : 9090
